### ISSUE TITLE
Add locate dns

### ISSUE THREAD

**Issue by Choirrulloh** [ultrapasty/dns-checker#3]
Hi,

How do I add a country location in the dns checker,

For example: country of Indonesia

thank you

**Comment by realjoshharrison** [comment]
You can’t add specific countries I’m afraid, it just uses a list of servers from the service at http://www.dns-lg.com/nodes.json

**Comment by Choirrulloh** [comment]
Thank you.

**Comment by evil4u** [comment]
Just wget the file from dns-lg and added to your site and edit.

**Comment by Choirrulloh** [comment]
> Just wget the file from dns-lg and added to your site and edit.

I did it, but it didn't work.

**Comment by evil4u** [comment]
Did you change the path in the file and did you google for the DNS servers that you need to use.

**Comment by Choirrulloh** [comment]
I did not change it, adding to the additions.

Not google dns but Indonesian ISP dns.
